services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: drawr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  http-backend:
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/drawr
      - JWT_SECRET=123123
    depends_on:
      - db

  ws-backend:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/drawr
      - JWT_SECRET=123123
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/excelidraw-frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    depends_on:
      - http-backend
      - ws-backend

volumes:
  postgres_data: